WidgetsExample:

<WidgetsExample>:
    cols: 3
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: str(int(my_slider.value))
            font_size: "120dp"
        Slider:
            id: my_slider
            min: 0
            max: 100
            disabled: not my_switch.active
            size_hint_y:
        Switch:
            id: my_switch
            on_active: root.on_switch_active(self)
            active: True
